export const REQUESTED_FETCH_LIST = "REQUESTED_FETCH_LIST";
export const SUCCESS_FETCH_LIST = "SUCCESS_FETCH_LIST";
export const FAILURE_FETCH_LIST = "FAILURE_FETCH_LIST";
export const GET_TABLE_COLUMNS = "GET_TABLE_COLUMNS";
export const UPDATE_TABLE_COLUMNS = "UPDATE_TABLE_COLUMNS";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const GET_FILTERING = "GET_FILTERING";
